#!/bin/bash
set -e

TEMPLATED_RUNTIME_LIB_DIR=/var/lib/proxmox-templated-vms

# shellcheck source=/dev/null
. "$TEMPLATED_RUNTIME_LIB_DIR"/functions

# shellcheck source=/dev/null
. "$TEMPLATED_RUNTIME_LIB_DIR"/linux/functions

exec entrypoint "$@"