#!/bin/sh

# shellcheck shell=bash

#################################################
# Environment vars
#################################################

# where log to
log_file="${TEMPLATED_LOG_FILE:-/var/log/templated.log}"

pre_start() {
	info "starting templated main function"
}

start_exec() {
    exec_log "pre-start hook" pre_start || return

    exec_log "receiving host" receive_host_data || return

    is_template_vm && info 'inside a template vm, exiting' && return 0

	exec_log "formats and mounts disk partition" \
        ensure_formated_and_mounted || return "$?"

	exec_log "initializes user data" \
        setup_vm_user_data || return "$?"

	exec_log "mounts user home directory" \
        mount_user_home_dir || return "$?"

    exec_log "post-start hook" post_start || return "$?"
}

post_start() {
	start_user_custom_config
}

templated_exec() {
	# set global user
	user="$1"

	if [ -z "$user" ]; then
        echo "Usage: maybe-start-templated-vm USER"
        return 1
    fi

    exec_log "main function" start_exec >> "$log_file" 2>&1
}
