#!/bin/sh

# shellcheck shell=bash
# shellcheck disable=SC2154


not_empty() {
    [ -n "$not_empty" ]
}

mounted() {
    df --output='target' | grep "^${mounted}$" 2> /dev/null
}

has_default_rw_directories() {
    local expected_dirs=('config' 'binds' 'home')
    for directory in "${expected_dirs[@]}"; do
        test -d "$has_default_rw_directories/$directory"
    done
}

is_disk() {
    ! is_raw_disk "$is_disk"
}

same_contents() {
    checksum() {
        sha256sum "$1" | awk '{print $1}'
    }

    [ "$(checksum "$1")" == "$(checksum "$2")" ]
}