#!/bin/sh

# shellcheck shell=bash

not_empty() {
    [ -n "${not_empty:?}" ]
}

mounted() {
    df --output='target' | grep "^${mounted:?}$" 2> /dev/null
}

has_default_rw_files() {
    local expected_dirs=('config' 'binds' 'home')
    local target
    target="${rw_dir:?}"

    for directory in "${expected_dirs[@]}"; do
        test -d "$target/$directory" || err "missing dir: $directory"
    done

    test -f "$target"/config/rc.local || err "missing rc.local"
    test "$(stat --format=%a "$target"/config/rc.local)" = 755 || \
        err "wrong rc.local permission" 

    test -f "$target"/config/bind-dirs.manifest || err "missing bind-dirs.manifest"
    test "$(stat --format=%a "$target"/config/bind-dirs.manifest)" = 644 || \
        err "wrong bind-dirs.manifest permission"
}

testit() {
    test "${testit:?}" "$1" "$2"
}

is_disk() {
    ! is_raw_disk "${is_disk:?}"
}

same_contents() {
    checksum() {
        sha256sum "$1" | awk '{print $1}'
    }

    [ "$(checksum "$1")" == "$(checksum "$2")" ]
}

is_owner() {
    local perm uid gid

    uid="$(id -u "$1")"
    gid="$(id -g "$1")"
    perm="$(stat --format="%u %g" "$2")"

    [ "$uid $gid" == "$perm" ]
}