#!/bin/sh

# shellcheck shell=bash
# shellcheck disable=SC2154


not_empty() {
    [ -n "$not_empty" ]
}

mounted() {
    df --output='target' | grep "^${mounted}$" 2> /dev/null
}

is_disk() {
    ! is_raw_disk "$is_disk"
}