#!/bin/bash 

# sanity check, disable real device formating
# shellcheck disable=SC2034
TEMPLATED_DEV=/dev/null

# shellcheck disable=SC1091
. ./unix/linux/functions

# default first partition offset
default_part_offset=$(( 2048 * 512 ))

loop_mount() {
    local device mntpoint
    device="${1%1}"
    mntpoint="$2"

    mount -o rw,loop,offset="$default_part_offset" "$device" "$mntpoint"
}

with_raw_disk_formated() {
    # shellcheck disable=SC2154
    format_disk_when_raw "$test_disk" "$test_disk" \
        -F -E offset="$default_part_offset" 2> /dev/null
}